name: test_pubg
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  get_it: ^7.2.0
  file_picker: ^5.2.2
  provider: ^6.0.4
  firebase_storage: ^11.0.2
  firebase_auth: ^4.0.2
  firebase_analytics: ^10.0.2
  cloud_firestore: ^4.0.2
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
 
  assets:
    - assets/images/